image:
  tag: 1.0.2001102238-sha.0708db8

replicas: 1

requests:
  cpu: 100m
  memory: 128Mi

logLevel: debug

useConnectString: false

logDNA:
    name: dev-insys-onboarding-service

useConnectString: false

postgres:
  maxConnectionLifetime: 10m
  maxIdleConnections: 1
  maxOpenConnections: 2
  logQueries: true
  dbPrimaryAddr: dev-pgsql-service-1a:5432
  dbReplicaAddr: dev-pgsql-service-1a:5432
  dbName: services
