image:
  tag: 1.0.1905281958-sha.26d7c07
  registry: gcr.io/weave-lab/insys/insys-onboarding-service

replicas: 1

requests:
  cpu: 100m
  memory: 128Mi

probes:
  port: 4444

logLevel: info

useConnectString: true

logDNA:
    name: insys-onboarding-service

postgres:
  maxConnectionLifetime: 30m
  maxIdleConnections: 0
  maxOpenConnections: 15
  logQueries: false
  dbPrimaryAddr: pgsql-service-1a:5432
  dbReplicaAddr: pgsql-service-1b:5432
