image:
  tag: 1.0.1903251623-sha.93e604b

replicas: 1

requests:
  cpu: 100m
  memory: 128Mi

logLevel: debug

useConnectString: false

postgres:
  maxConnectionLifetime: 10m
  maxIdleConnections: 0
  maxOpenConnections: 10
  logQueries: true
  dbPrimaryAddr: dev-pgsql-service-1a:5432
  dbReplicaAddr: dev-pgsql-service-1a:5432
