image:
  tag: 1.0.1910091710-sha.de83101
  registry: gcr.io/weave-lab/insys/insys-onboarding-service

replicas: 3

requests:
  cpu: 100m
  memory: 128Mi

probes:
  port: 4444

logLevel: info

useConnectString: false

logDNA:
    name: insys-onboarding-service

postgres:
  maxConnectionLifetime: 30m
  maxIdleConnections: 2
  maxOpenConnections: 15
  logQueries: false
  dbPrimaryAddr: pgsql-service-1a:5432
  dbReplicaAddr: pgsql-service-1b:5432
